imageCredentials:
  dockeryuuvisorg:
    registry: docker.yuuvis.org
    username:
    password:

yuuvis:
  # !!! Change before running
  # replace the value with the namespace you intent to use for the yuuvis API services
  # this chart creates a k8s job that generatey a selfsigned certificate and deploys the
  # crt file as a secret to the given namespace
  namespaces: 
    yuuvis: yuuvis
    infrastructure: infrastructure
  authentication:
    # we assume test deployment in minikube
    # ip is the ip of the vm minikube creates
    # to get the ip: minikube ip
    ip: 192.168.99.100
    port: 30080
  labels:
    app: yuuvis
  db:
    user: yuuvis
    password: changeme
  keycloak:
    user: keycloak
    password: changeme
    db:
      user: keycloak
      password: changeme
    nodePort: 30111
    realm:
      yuuvistest:
        user:
          name: root
          password: changeme
      testyuuvis:
        user:
          name: root
          password: changeme

postgresql:
  enabled: true
  fullnameOverride: postgresql
  postgresqlPassword: changeme
  persistence:
    storageClass: standard
    size: 500Mi
  resources:
    requests:
      memory: 128Mi
      cpu: 50m
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  initdbScriptsConfigMap: postgresql-initdb
  postgresqlExtendedConf: {"max_connections": "400", "shared_buffers": "128MB"}



gogs:
  useCustomDeployment: true
  image: gogs/gogs:0.11.91
  imagePullPolicy: IfNotPresent
  persistence:
    size: 500Mi
    storageClass: standard
  git:
    user: yuuvis
    password: changeme
    
keycloak:
  enabled: true
  fullnameOverride: "keycloak"
  image.repository: jboss/keycloak
  image.tag: 11.0.3
  livenessProbe: |
    httpGet:
      path: /auth/
      port: http
    initialDelaySeconds: 600
    timeoutSeconds: 5
  postgresql:
    enabled: false
  extraEnv: |
    - name: KEYCLOAK_USER_FILE
      value: /secrets/keycloak/user
    - name: KEYCLOAK_PASSWORD_FILE
      value: /secrets/keycloak/password
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: postgresql
    - name: DB_PORT
      value: "5432"
    - name: DB_DATABASE
      value: keycloak
    - name: DB_USER_FILE
      value: /secrets/db-creds/user
    - name: DB_PASSWORD_FILE
      value: /secrets/db-creds/password
    - name: KEYCLOAK_IMPORT
      value: "/realm/yuuvistest.json,/realm/testyuuvis.json -Dkeycloak.profile.feature.upload_scripts=enabled"
  extraVolumes: |
    - name: realm-config
      configMap:
        name: realmconfigmap
    - name: db-creds
      secret:
        secretName: keycloakdb
    - name: kc-creds
      secret:
        secretName: keycloakuser
  extraVolumeMounts: |
    - name: realm-config
      mountPath: "/realm/"
      readOnly: true
    - name: db-creds
      mountPath: /secrets/db-creds
      readOnly: true
    - name: kc-creds
      mountPath: /secrets/keycloak
      readOnly: true

redis:
  fullnameOverride: redis
  ## Cluster settings
  cluster:
    enabled: false
  usePassword: false
  master:
    livenessProbe:
      initialDelaySeconds: 600
    persistence:
      enabled: false
      storageClass: standard
      size: 50Mi
